### PR TITLE
build: Bump bootstrap 4.6.2

### PR DESCRIPTION
**Pull request by AiyionPrime**
So this is the breaking version bump from bootstrap three to four.

Several names of classes changed, it is likely that I've missed something.

~Currently the scrollspy feature is not working.~

### CODE REVIEW

**Comment by AiyionPrime** [comment]
Cache issue. The scrollspy is working just fine. This is ready for review :)

**Comment by AiyionPrime** [comment]
I think that's it.
The scroll spy applied the active class to the list elements, now to then links itself.
Stylesheet was updated accordingly, this is ready for review.

**Comment by AiyionPrime** [comment]
This also gets rid of the console warning of non-std feature `zoom`.

**Review by ctandi — APPROVED** [review]
Checked this on my 2 inch smartwatch. Seems solid! Way to go, Aiyion!

**Review by 1977er — APPROVED** [review]
LGTM - though I have no webdesign skills, the website still seems to work. Minor differences in renderings (ie. margins), but no version is "better" than the other.

**Pull request merged**
